"""Added shift_code_ref table

Revision ID: 1d097a05c742
Revises: 9159516a2548
Create Date: 2023-11-06 11:51:58.799496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d097a05c742'
down_revision = '9159516a2548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_code_ref',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('productive', sa.Boolean(), nullable=True),
    sa.Column('orientation', sa.Boolean(), nullable=True),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.alter_column('date_detail',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.alter_column('date_detail',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    op.drop_table('shift_code_ref')
    # ### end Alembic commands ###
