"""Added ldap_user_data table

Revision ID: 3a4e4987088d
Revises: 495eb760e66e
Create Date: 2023-10-31 14:23:46.854525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4e4987088d'
down_revision = '495eb760e66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldap_user_data',
    sa.Column('uciUCNetID', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=True),
    sa.Column('uciCampusID', sa.String(length=12), nullable=True),
    sa.Column('displayName', sa.String(length=60), nullable=True),
    sa.Column('sn', sa.String(length=60), nullable=True),
    sa.Column('givenName', sa.String(length=60), nullable=True),
    sa.Column('middleName', sa.String(length=60), nullable=True),
    sa.Column('uciPublishedTitle1', sa.String(length=60), nullable=True),
    sa.Column('uciAffiliation', sa.String(length=100), nullable=True),
    sa.Column('uciPrimaryDepartmentCode', sa.String(length=10), nullable=True),
    sa.Column('uciPrimaryDepartment', sa.String(length=30), nullable=True),
    sa.Column('uciLevel3DepartmentDescription', sa.String(length=30), nullable=True),
    sa.Column('ou', sa.String(length=60), nullable=True),
    sa.Column('uciMailDeliveryPoint', sa.String(length=60), nullable=True),
    sa.Column('uciPublishedOfficeAddress1', sa.String(length=60), nullable=True),
    sa.Column('uciPublishedDepartment1', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uciUCNetID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ldap_user_data')
    # ### end Alembic commands ###
