"""Added display_label column

Revision ID: 495eb760e66e
Revises: efdc20a4f0d2
Create Date: 2023-10-30 16:48:00.223895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495eb760e66e'
down_revision = 'efdc20a4f0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_location_label', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('display_location_label')

    # ### end Alembic commands ###
