"""ADDED location_id to daily_schedule_data table

Revision ID: 558e13dfcde2
Revises: 3de49a063a79
Create Date: 2023-11-29 11:55:07.305482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558e13dfcde2'
down_revision = '3de49a063a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('assignment_id')

    # ### end Alembic commands ###
