"""ADDED Time and duration in hours

Revision ID: 5a19e52e7f35
Revises: 9a5ba771d172
Create Date: 2023-11-27 14:36:02.148089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a19e52e7f35'
down_revision = '9a5ba771d172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_assignment_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('daily_assignment_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('daily_assignment_hours')
        batch_op.drop_column('daily_assignment_start')

    # ### end Alembic commands ###
