"""setup uid fullname mappings

Revision ID: 645de521517a
Revises: 558e13dfcde2
Create Date: 2023-11-29 16:00:20.577156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645de521517a'
down_revision = '558e13dfcde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_ldap_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_employee_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_competencies_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_competencies_id'], ['employee_competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('assignment_id')

    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.drop_column('assignment_id')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('assignment_employee_competencies')
    op.drop_table('report_ldap_mappings')
    op.drop_table('employee_competencies')
    # ### end Alembic commands ###
