"""ADDED display order to shift template

Revision ID: 8081700aef5f
Revises: 5a19e52e7f35
Create Date: 2023-11-27 16:01:33.865599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8081700aef5f'
down_revision = '5a19e52e7f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_template', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
