"""Added metadata columns to DailyScheduleData

Revision ID: 9159516a2548
Revises: f9c29a8e6f37
Create Date: 2023-11-02 16:42:17.810346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9159516a2548'
down_revision = 'f9c29a8e6f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('record_uploaded_by', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.drop_column('record_uploaded_by')
        batch_op.drop_column('record_uploaded_at')

    # ### end Alembic commands ###
