"""removed foreign key from ldap table

Revision ID: 9a5ba771d172
Revises: fc323acf9a17
Create Date: 2023-11-06 17:03:47.190362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5ba771d172'
down_revision = 'fc323acf9a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_data', schema=None) as batch_op:
        batch_op.drop_constraint('ldap_user_data_uid_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_data', schema=None) as batch_op:
        batch_op.create_foreign_key('ldap_user_data_uid_fkey', 'user', ['uid'], ['username'])

    # ### end Alembic commands ###
