"""Employee tables and license certs

Revision ID: be9061c89b96
Revises: 1d097a05c742
Create Date: 2023-11-06 13:22:47.687895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9061c89b96'
down_revision = '1d097a05c742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ed_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('licenses_and_certs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift_role_ref',
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role'),
    sa.UniqueConstraint('role')
    )
    op.create_table('ed_staff_licenses_and_certs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('license_or_cert_id', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['license_or_cert_id'], ['licenses_and_certs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['ed_staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_code_ref', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_code_ref', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('ed_staff_licenses_and_certs')
    op.drop_table('shift_role_ref')
    op.drop_table('licenses_and_certs')
    op.drop_table('ed_staff')
    # ### end Alembic commands ###
