"""Added relationships between tables

Revision ID: de62e8246a0e
Revises: 3a4e4987088d
Create Date: 2023-11-01 15:32:38.687601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de62e8246a0e'
down_revision = '3a4e4987088d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['uid'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
