"""added display color column to location

Revision ID: efdc20a4f0d2
Revises: c0d9222819a0
Create Date: 2023-10-30 15:07:52.408420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdc20a4f0d2'
down_revision = 'c0d9222819a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_color', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('display_color')

    # ### end Alembic commands ###
