"""defined DailyScheduleData Table

Revision ID: f9c29a8e6f37
Revises: de62e8246a0e
Create Date: 2023-11-01 17:43:55.520068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c29a8e6f37'
down_revision = 'de62e8246a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_schedule_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('coverage_period', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('date_detail', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('assignment', sa.String(length=100), server_default='unassigned', nullable=True),
    sa.PrimaryKeyConstraint('date', 'coverage_period', 'name', 'code')
    )
    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_schedule_data_date'), ['date'], unique=False)

    with op.batch_alter_table('user_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_detail', schema=None) as batch_op:
        batch_op.drop_column('department')

    with op.batch_alter_table('daily_schedule_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_schedule_data_date'))

    op.drop_table('daily_schedule_data')
    # ### end Alembic commands ###
